### PR TITLE
Add redhat repo to pom

### PR DESCRIPTION
**Pull request by CMoH**
This helps users that don't have redhat's GA configured in settings.xml build and use amqutil

### CODE REVIEW

**Review by kevinboone — APPROVED** [review]

**Comment by kevinboone** [comment]
I wonder if a better approach that adding the Red Hat repo to pom.xml would be to use only the upstream version of qpid-jms ? (I guess that is where the problem is) The Red Hat version had the latest fixes (I think) when I added that section of code, but it isn't a foregone conclusion that it always will.

Comments welcome.

**Comment by CMoH** [comment]
Version 0.40.0 is indeed available on maven central. I have pushed a commit that removes the redhat-ga repository definition from the pom, and bumps the dependency. It builds on my machine, but I have not tested the end result (I am not a qpid user).

I can squash the commits if you find this change works for you, or drop it if you want to go with redhat's version.

**Comment by kevinboone** [comment]
This seems reasonable, but please allow me some time to check that this 
version works with my AMQP tests.

**Comment by kevinboone** [comment]
I just committed an update with qpid-jms (upstream) 0.40.0 and with a 
.gitignore file to exclude target/.

I suspect that there are bug fixes in the Red Hat branch of qpid-jms 
that are not present even in the latest upstream releases. The same is 
probably true for the ActiveMQ (OpenWire) client runtime. Still, if 
folks want to use a Red Hat version of any of these libraries, they 
probably know how to edit the dependencies themselves.

**Comment by CMoH** [comment]
OK! Then I suppose I can close this issue. Thanks!

**Pull request closed without merging**
